name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/fork-sync-with-upstream-action@v3.4.3
        with:
          upstream_sync_repo: fish2018/pansou
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Sync failed due to workflow change or merge conflict, please sync manually"
          exit 1
